# Purpose:       config file for zsh)
#
#Site        :https://renantmagalhaes.net
#Author      :Renan Toesqui Magalhães <renantmagalhaes@gmail.com>
#                                     <https://github.com/renantmagalhaes>
#
# ---------------------------------------------------------------
#
# Changelog
#
#   V0.1 2019-01-30 RTM:
#       - Initial release
#
#   TODO
#   * 


#RTM

# Path to your oh-my-zsh installation.
export ZSH="/home/$USER/.oh-my-zsh"

# Set theme
POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"


#Plugins

plugins=(
  git
  kubectl
  kube-ps1
  zsh-completions
  zsh-autosuggestions
  colored-man-pages
  colorize
  command-not-found
  docker
  docker-compose
  tmux

)


# Configure env kubectl
source "$ZSH/plugins/kube-ps1/kube-ps1.plugin.zsh"
prompt_kube_ps1(){
   echo -n `kube_ps1`
}
KUBE_PS1_NS_ENABLE="false"
KUBE_PS1_DIVIDER=""
KUBE_PS1_SYMBOL_USE_IMG="\u2638"

# Display

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_user dir_writable dir vcs)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status background_jobs command_execution_time kubecontext )
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status background_jobs command_execution_time custom_command)


POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=3

## User with skull
user_with_skull() {
    echo -n "\uf1d0 $(whoami)@$(hostname)"
}
POWERLEVEL9K_CUSTOM_USER="user_with_skull"

#Kubecontext
read_kube_config_context() {
	    cat ~/.kube/config |grep name |tail -n2 |awk {'print $3'}
    }
POWERLEVEL9K_CUSTOM_COMMAND="read_kube_config_context"


#Colors

## DIRS
POWERLEVEL9K_DIR_HOME_BACKGROUND='black'
POWERLEVEL9K_DIR_HOME_FOREGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='black'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='white'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='yellow'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='black'

## VCS icons
POWERLEVEL9K_VCS_GIT_ICON=$'\uf1d2 '
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=$'\uf171 '
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=$'\uf113 '
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=$'\uf296 '
POWERLEVEL9K_VCS_BRANCH_ICON=$''
POWERLEVEL9K_VCS_STAGED_ICON=$'\uf055'
POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\uf421'
POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\uf00d'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$'\uf0ab '
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$'\uf0aa '

## VCS colours
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='black'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='green'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='black'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='green'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='black'

## command_execution_time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='black'

## kunnecontext
POWERLEVEL9K_KUBECONTEXT_BACKGROUND='white'
POWERLEVEL9K_KUBECONTEXT_FOREGROUND='black'


#characters backspace 
#WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

#Custom plugins
source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source $ZSH/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh


#source
source $ZSH/oh-my-zsh.sh
